source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'coffee-rails'
gem 'devise'
gem 'mongoid'
gem 'mongoid-tree'
gem 'newrelic_rpm'
gem 'pg'
gem 'pry'
gem 'rails', '4.1.5'
gem 'sass-rails', '~> 4.0.3'
gem 'twitter-bootstrap-rails'
gem 'therubyracer',  platforms: :ruby
gem 'uglifier', '>= 1.3.0'


gem 'rails-assets-angular', '1.3.0.beta.10'
# gem 'rails-assets-angular-route', '1.3.0.build.2767.sha.3fc95e0'
gem 'rails-assets-angular-resource', '1.3.0.beta.10'
gem 'rails-assets-jquery', '1.9.1'
gem 'rails-assets-jquery-ujs'
gem 'rails-assets-kendo-ui-core'



# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'quiet_assets',        group: :development


group :production do 
  gem 'rails_12factor'
end
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

