source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '4.0.5'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'

gem 'rails-assets-bootstrap'
gem 'rails-assets-angular'

gem 'therubyracer'
gem 'mongoid'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development


gem 'debugger', group: [:development, :test]
